'''
When run, this file reads through the responses in the response directory,
parses them for non-answer features like length and rating hallucinations, and
records the results in the 'response_features' subdirectory of the evaluation
directory. If any model/problem set/frame combination already has a
corresponding file in the response features directory, it will not be
re-evaluated unless the file is deleted. Any model/problem set/frame
combination evaluated by this file is expected to already have a corresponding
file generated by evaluate.py in the base evaluation directory. As this file
executes, it will generate text files in the 'false_rating _statements'
subdirectory of the response features directory, recording apparent rating
hallucinations found by an automatic parser. These text files have labeled
places where manual assessments can be written in, and these will be
incorporated into this file's output if the relevant model/problem set/frame
combinations are re-evaluated. In these places, write "false positive" for
erroneously detected rating hallucinations.

This file does not run with any arguments.
'''

from os import path, listdir, makedirs, remove
import re
import itertools
import numpy as np

from metadata import *
from utils import get_clean_tokens, string_to_grouping,\
     string_to_preference_matrix, rating_set_to_string,\
     grouping_is_stable, has_stable_groupings

clause_sep_re = re.compile(r"((\.\D)|(,\D)|:|;|\?|!)")
no_re = re.compile(r"\bno\b|\bnot\b|\bnor\b|n't\b|\bnon|\bnowhere\b")
digits_re = re.compile(r"\d+")
paren_re = re.compile(r"\((\w| |')+\)")

def starts_with_any(string, prefixes):
  for prefix in prefixes:
    if string.startswith(prefix):
      return True
  return False

def ends_with_any(string, suffixes):
  for suffix in suffixes:
    if string.endswith(suffix):
      return True
  return False

def contains_any_whole_word(string, words):
  escaped_words = [re.escape(w) for w in words]
  pattern = re.compile(r'\b(' + '|'.join(escaped_words) + r')\b')
  return pattern.search(string) is not None

def replace_each_whole_word(string, replace_dict):
  escaped_keys = [re.escape(k) for k in replace_dict.keys()]
  pattern = re.compile(r'\b(' + '|'.join(escaped_keys) + r')\b')
  return pattern.sub(lambda match: replace_dict[match.group()], string)

def rs_preamble_search(string, index, boundary, clause_seps):
  paren_depth = 0
  preamble_chars = []
  index -= 1
  
  while index >= boundary:
    if paren_depth == 0 and index in clause_seps:
      break
    
    if string[index] == ')':
      paren_depth += 1
    
    if paren_depth == 0:
      preamble_chars.append(string[index])
    else:
      preamble_chars.append(' ')
    
    if string[index] == '(':
      paren_depth -= 1
      if paren_depth < 0:
        preamble_chars.pop()
        break
    
    index -= 1
  
  return index + 1, ''.join(reversed(preamble_chars))

def rs_postscript_search(string, index, boundary, clause_seps):
  paren_depth = 0
  postscript_chars = []
  
  while index < boundary:
    if paren_depth == 0 and index in clause_seps:
      postscript_chars.append(string[index])
      break
    
    if string[index] == '(':
      paren_depth += 1
    
    if paren_depth == 0:
      postscript_chars.append(string[index])
    else:
      postscript_chars.append(' ')
    
    if string[index] == ')':
      paren_depth -= 1
      if paren_depth < 0:
        postscript_chars.pop()
        break
    
    index += 1
  
  return index, ''.join(postscript_chars)

def rs_preamble_invalidity_heuristic(string):
  if string == 'is':
    return True
  
  if no_re.search(string) is not None:
    return True
  
  if contains_any_whole_word(string, ['if', 'whether', 'or', 'possible']):
    return True
  
  return False

def find_rating_statements(model, problem_set, frame, filename, lines):
  n = problem_set['n']
  k = problem_set['k']
  
  if frame == 'roommates':
    return frs_roommates(n, k, lines)
  
  return None

def do_manual_frs_search(model, problem_set, frame, filename, grouping,
                         evaluation):
  return False

re1 = re.compile(r"\[#\d+\](( |: ?)(rates|likes)|'s ratings)( |: ?)")
re2 = re.compile(r"(\[#\d+\] ?(:|a|as|=|-)? ?\d+,? ?)+(and \[#\d+\] ?(:|a|as|=|-)? ?\d+)?")
re3 = re.compile(r"\b([A-Za-z]+)(\d+)")
re4 = re.compile(r"(\[#\d+\])([A-Za-z]| |')* (to|with|from|roommates|new:) (\[#\d+\])( ?, ?| and )(\[#\d+\]):")
re5 = re.compile(r"\b(to|with) (\[#\d+\]) and (\[#\d+\]):")
re6_rating_block = r"((rating )?\[#\d+\]( ?->? ?| rates )\[#\d+\]|\b(R|r)(ating)?(\(|\[) ?\[#\d+\] ?(,|(\)|\])(\(|\[)) ?\[#\d+\] ?(\)|\]))"
re6 = re.compile(re6_rating_block + r" ?\+ ?" + re6_rating_block + r" ?= ?\d+ ?\+ ?\d+")
re6_left_side = re.compile(re6_rating_block + r" ?\+ ?" + re6_rating_block)
re6_multiple = re.compile(r"(" + re6_rating_block + r" ?\+ ?){2,}" + re6_rating_block)
re7 = re.compile(r"\[#\d+\] ?-> ?\[#\d+\] \d+|" + re6_rating_block + r" ?(:|=) ?\d+")
re8_rating_block = r"\[#\d+\] ?(: ?\d+|\(\d+\))"
re8 = re.compile(r"\[#\d+\]('s )?((new )?satisfaction)?( ?in [A-Za-z]+ ?\d*)?: ?" + re8_rating_block + r" ?\+ ?" + re8_rating_block)
re8_multiple = re.compile(r"(" + re8_rating_block + r" ?\+ ?){2,}" + re8_rating_block)
re9 = re.compile(r"\[#\d+\]('s)?( rating)? for \[#\d+\] ?(\+|and) ?\[#\d+\] ?(=|:) ?\d+ ?\+ ?\d+")
re10 = re.compile(r" ?(-|\+) ?\d+")
re11 = re.compile(r"pair|edge|comb(o|ination)|high(est)? mutual|mutual (rating|score|total|sum|contribution|high)|\bMR\b|\b(w|s)( value|_\{|\(([A-Z]|\[#\d+\]),)|weight|satisfaction sum", re.IGNORECASE)
re12 = re.compile(r"sum|others|etc|R\d+-R\d+|(For |- ?)[A-Z]=\[#\d+\]|\[#\d+\] ?(,|-)? ?(\[#\d+\]|X|\?)")
re13 = re.compile(r"(T|t)riple|\[#\d+\], ?\[#\d+\], ?(\[#\d+\]|X|\?)|\[#\d+\] ?- ?\[#\d+\] ?- ?(\[#\d+\]|X|\?)|\[#\d+\] \[#\d+\] (\[#\d+\]|X|\?)")
re14 = re.compile(r"(\b|_)([A-Z])([A-Z])\b")
re15 = re.compile(r"\[#\d+\] ?- ?\[#\d+\]")

def _add_statement(statements, e1, e2, value, line_index):
  if e1 != e2:
    statement = (e1, e2, value)
    if line_index not in statements:
      statements[line_index] = {} # dict to preserve insertion order
    elif statement in statements[line_index]:
      del statements[line_index][statement]
    statements[line_index][statement] = True

def frs_roommates(n, k, lines):
  names = male_names[:(n * k)]
  names_replace = {}
  for i, name in enumerate(names):
    code = '[#' + str(i) + ']'
    names_replace[name] = code
    names_replace[name[0]] = code
  
  statements = {}
  pair_discussion_state = -1
  
  for i in range(len(lines)):
    line = lines[i].strip()
    
    if len(line) == 0:
      continue
    
    line = re3.sub(lambda match: match.group(1) + ':' + match.group(2)\
                   if match.group(1) in names_replace else match.group(), line)
    line = re14.sub(lambda match: match.group(1)\
                    + names_replace[match.group(2)]\
                    + names_replace[match.group(3)]\
                    if match.group(2) in names_replace and match.group(3)\
                    in names_replace else match.group(), line)
    line = replace_each_whole_word(line, names_replace)
    line = re4.sub(lambda match: match.group(1), line)
    line = re5.sub('', line)
    line = re6_multiple.sub('', line)
    line = re8_multiple.sub('', line)
    
    if re11.search(line) is None and re13.search(line) is None:
      if pair_discussion_state >= 0:
        if re12.search(line) is None:
          pair_discussion_state += 1
          if pair_discussion_state > 1:
            pair_discussion_state = -1
        else:
          pair_discussion_state = 0
    else:
      pair_discussion_state = 0
    
    if pair_discussion_state >= 0:
      line = re13.sub('', line)
      line = re15.sub('', line)
    
    re6_locs = [m.span() for m in re6.finditer(line)]
    
    for j in range(len(re6_locs)):
      start, end = re6_locs[j]
      if line[end:].startswith('?'):
        continue
      numbers = [int(m.group()) for m in digits_re.finditer(line[start:end])]
      _add_statement(statements, numbers[0], numbers[1], numbers[4], i)
      _add_statement(statements, numbers[2], numbers[3], numbers[5], i)
    
    line = re6_left_side.sub('', line)
    
    e1_locs = [m.span() for m in re1.finditer(line)]
    
    if len(e1_locs) > 0:
      clause_seps = set(m.start() for m in clause_sep_re.finditer(line))
      preamble_boundary = 0
      
      for j in range(len(e1_locs)):
        e1_start, e1_end = e1_locs[j]
        if j == len(e1_locs) - 1:
          e2_area_end = len(line)
        else:
          e2_area_end = e1_locs[j + 1][0]
        
        _, preamble = rs_preamble_search(
          line, e1_start, preamble_boundary, clause_seps)
        preamble = preamble.strip()
        
        if rs_preamble_invalidity_heuristic(preamble):
          continue
        
        e2m = re2.match(line, e1_end, e2_area_end)
        
        if e2m is None:
          continue
        
        e2m_start, e2m_end = e2m.span()
        preamble_boundary = e2m_end
        _, postscript = rs_postscript_search(
          line, e2m_end, e2_area_end, clause_seps)
        
        if starts_with_any(postscript, ['st', 'nd', 'th']):
          continue
        
        postscript = postscript.strip()
        
        if starts_with_any(postscript, ['if', 'only if'])\
        or postscript.endswith('?')\
        or (preamble.endswith('"') and postscript.startswith('"'))\
        or (preamble.endswith('“') and postscript.startswith('”')):
          continue
        
        e1 = int(digits_re.search(line, e1_start, e1_end).group())
        e2v_list = [int(m.group())\
                    for m in digits_re.finditer(line[e2m_start:e2m_end])]
        e2_set = set()
        
        for a in range(0, len(e2v_list), 2):
          e2 = e2v_list[a]
          v = e2v_list[a + 1]
          if e2 not in e2_set:
            e2_set.add(e2)
            _add_statement(statements, e1, e2, v, i)
    
    re7_locs = [m.span() for m in re7.finditer(line)]
    
    for j in range(len(re7_locs)):
      start, end = re7_locs[j]
      if line[end:].startswith('?')\
      or re10.match(line, end) is not None\
      or ends_with_any(line[:start], [']', ']-', 'pair ', 'with ', '+', '+ ']):
        continue
      numbers = [int(m.group()) for m in digits_re.finditer(line[start:end])]
      _add_statement(statements, numbers[0], numbers[1], numbers[2], i)
    
    re8_locs = [m.span() for m in re8.finditer(line)]
    
    for j in range(len(re8_locs)):
      start, end = re8_locs[j]
      if line[end:].startswith('?'):
        continue
      numbers = [int(m.group()) for m in digits_re.finditer(line[start:end])]
      if len(numbers) == 6: # It'll be either 5 or 6
        numbers.pop(1)
      _add_statement(statements, numbers[0], numbers[1], numbers[2], i)
      _add_statement(statements, numbers[0], numbers[3], numbers[4], i)
    
    re9_locs = [m.span() for m in re9.finditer(line)]
    
    for j in range(len(re9_locs)):
      start, end = re9_locs[j]
      if line[end:].startswith('?'):
        continue
      numbers = [int(m.group()) for m in digits_re.finditer(line[start:end])]
      _add_statement(statements, numbers[0], numbers[1], numbers[3], i)
      _add_statement(statements, numbers[0], numbers[2], numbers[4], i)
  
  return statements

for model in models:
  for problem_set in problem_sets:
    ps_short_name = problem_set['short_name']
    n = problem_set['n']
    k = problem_set['k']
    nk = n * k
    
    if 'search_for_frs' in problem_set:
      search_for_frs = problem_set['search_for_frs']
    else:
      search_for_frs = 'all'
    
    ps_data_dir = path.join(data_dir, ps_short_name)
    mps_response_dir = path.join(response_dir, model, ps_short_name)
    
    if not path.exists(ps_data_dir) or not path.exists(mps_response_dir):
      continue
    
    features_file_paths = []
    false_rs_file_paths = []
    manual_frs_paths = []
    mps_frame_indices = []
    repeat_dirs = []
    
    for i in range(len(frames)):
      f_response_dir = path.join(mps_response_dir, frames[i])
      f_filename = '%s_%s_%s.txt' % (model, ps_short_name, frames[i])
      features_file_paths.append(path.join(evaluation_dir, 'response_features',
                                           f_filename))
      false_rs_file_paths.append(path.join(evaluation_dir, 'response_features',
        'false_rating_statements', f_filename))
      manual_frs_paths.append(path.join(evaluation_dir, 'response_features',
        'manual_frs_searches', model, ps_short_name, frames[i]))
      
      if not path.exists(f_response_dir)\
      or path.exists(features_file_paths[-1]):
        continue
      
      mps_frame_indices.append(i)
      f_repeat_dirs = []
      
      for filename in listdir(f_response_dir):
        file_path = path.join(f_response_dir, filename)
        if path.isdir(file_path):
          f_repeat_dirs.append(file_path)
      
      if len(f_repeat_dirs) == 0:
        f_repeat_dirs.append(f_response_dir)
      
      repeat_dirs.append(f_repeat_dirs)
    
    if len(mps_frame_indices) == 0:
      continue
    
    print('Evaluating response features for %s %s' % (model, ps_short_name))
    
    filenames = list(listdir(ps_data_dir))
    filename_indices = {filenames[a]: a for a in range(len(filenames))}
    repeat_indices = [{path.basename(repeat_dirs[m][j]): j
                       for j in range(len(repeat_dirs[m]))}
                      for m in range(len(mps_frame_indices))]
    problem_prefs = [None for k in range(len(filenames))]
    features = [[[] for j in range(len(repeat_dirs[m]))]
                for m in range(len(mps_frame_indices))]
    evals = [[[None for f in filenames] for j in range(len(repeat_dirs[m]))]
             for m in range(len(mps_frame_indices))]
    overrides = [{} for m in range(len(mps_frame_indices))]
    manual_frs = [{} for m in range(len(mps_frame_indices))]
    
    for m in range(len(mps_frame_indices)):
      i = mps_frame_indices[m]
      
      eval_file_path = path.join(evaluation_dir,
        '%s_%s_%s.txt' % (model, ps_short_name, frames[i]))
      eval_file = open(eval_file_path, 'r')
      
      for line in eval_file:
        line = line.strip()
        
        if len(line) == 0:
          continue
        
        filename, repeat, num_stable, grouping, evaluation = line.split()
        
        problem_index = filename_indices[filename]
        repeat_index = repeat_indices[m][repeat]
        
        evals[m][repeat_index][problem_index] = (grouping, evaluation)
      
      eval_file.close()
      
      if path.exists(false_rs_file_paths[i]):
        false_rs_file = open(false_rs_file_paths[i], 'r', encoding='utf-8')
        lines = false_rs_file.read().splitlines()
        false_rs_file.close()
        
        li = -1
        current_line = None
        
        def advance():
          global li, current_line
          while True:
            li += 1
            
            if li >= len(lines):
              return True
            
            current_line = lines[li].strip()
            
            if len(current_line) != 0:
              return False
        
        def parse():
          global li, current_line
          if advance(): return
          while True:
            filename, repeat = current_line.split()
            overrides_key = (filename, repeat)
            if advance(): return
            while current_line != '---':
              line_index = int(current_line.split()[1]) - 1
              if advance(): return
              if advance(): return
              if advance(): return
              while current_line[-1] == ']':
                rating, current_line = current_line.split('[')
                assessment = current_line.split(':')[1]
                
                rating, v = rating.split(':')
                v = int(v.strip())
                rating = rating.strip().split('->')
                rating = tuple(char_indices[c.strip()] for c in rating)
                rating = (rating[0], rating[1], v)
                
                assessment = assessment[:-1].strip()
                
                if assessment != 'N/A':
                  if overrides_key not in overrides[m]:
                    overrides[m][overrides_key] = {}
                  if line_index not in overrides[m][overrides_key]:
                    overrides[m][overrides_key][line_index] = {}
                  overrides[m][overrides_key][line_index][rating] = assessment
                
                if advance(): return
            
            if advance(): return
        
        parse()
      '''
      if path.exists(manual_frs_paths[i]):
        for filename in listdir(manual_frs_paths[i]):
          mfrs_file_path = path.join(manual_frs_paths[i], filename)
          mfrs_file = open(mfrs_file_path, 'r', encoding='utf-8')
          lines = mfrs_file.read().splitlines()
          mfrs_file.close()
      '''
    for a in range(len(filenames)):
      filename = filenames[a]
      
      data_file_path = path.join(ps_data_dir, filename)
      data_file = open(data_file_path, 'r')
      lines = data_file.read().splitlines()
      data_file.close()
      
      prefs_str = '\n'.join(lines[:-1])
      prefs = string_to_preference_matrix(prefs_str)
      problem_prefs.append(prefs)
      
      for m in range(len(mps_frame_indices)):
        i = mps_frame_indices[m]
        for j in range(len(repeat_dirs[m])):
          response_file_path = path.join(repeat_dirs[m][j], filename)
          ev = evals[m][j][a]
          
          if not path.exists(response_file_path) or ev is None:
            features[m][j].append(None)
            continue
          
          response_file = open(response_file_path, 'r', encoding='utf-8')
          lines = response_file.read().splitlines()
          response_file.close()
          grouping, evaluation = ev
          
          length = 0
          
          for line in lines:
            if len(line) == 0:
              continue
            length += len(get_clean_tokens(line))
          
          repeat = path.basename(repeat_dirs[m][j])
          overrides_key = (filename, repeat)
          
          manual_frs_search = False
          rs_to_count = None
          true_ratings = None
          false_ratings = None
          would_be_correct = None
          rs_to_report = None
          
          if search_for_frs == 'all'\
          or (search_for_frs == 'incorrect' and evaluation == 'incorrect'):
            rating_statements = find_rating_statements(
              model, problem_set, frames[i], filename, lines)
            
            if rating_statements is None:
              manual_frs_search = do_manual_frs_search(
                model, problem_set, frames[i], filename, grouping, evaluation)
              if manual_frs_search and overrides_key in manual_frs[m]:
                rs_to_count = {rating: True
                               for rating in manual_frs[m][overrides_key]}
            else:
              rs_to_count = {} # dict to preserve insertion order
              rs_to_report = {}
              
              for li in sorted(rating_statements.keys()):
                for rating in rating_statements[li]:
                  e1, e2, v = rating
                  if rating not in rs_to_count and not (e1 >= 0 and e1 < nk\
                  and e2 >= 0 and e2 < nk and e1 != e2 and prefs[e1, e2] == v):
                    if li not in rs_to_report:
                      rs_to_report[li] = (lines[li], {})
                    rs_to_report[li][1][rating] = True
                  
                  if rating in rs_to_count:
                    del rs_to_count[rating]
                  rs_to_count[rating] = True
              
              if overrides_key in overrides[m]:
                file_overrides = overrides[m][overrides_key]
                for li, line_overrides in file_overrides.items():
                  for rating, assessment in line_overrides.items():
                    if assessment == 'false positive' and rating in rs_to_count:
                      del rs_to_count[rating]
            
            if rs_to_count is not None:
              true_ratings = set()
              false_ratings = set()
              num_invalid_ratings = 0
              for statement in rs_to_count:
                e1, e2, v = statement
                if e1 >= 0 and e1 < nk and e2 >= 0 and e2 < nk and e1 != e2:
                  if prefs[e1, e2] == v:
                    true_ratings.add(statement)
                  else:
                    false_ratings.add(statement)
                else:
                  false_ratings.add(statement)
                  num_invalid_ratings += 1
              
              if num_invalid_ratings > 0 or grouping.startswith('not_found'):
                would_be_correct = False
              elif len(false_ratings) == 0:
                would_be_correct = True
              else:
                alt_prefs = np.copy(prefs)
                for statement in rs_to_count:
                  e1, e2, v = statement
                  alt_prefs[e1, e2] = v
                
                if grouping == 'impossible':
                  would_be_correct = (not has_stable_groupings(n, k, alt_prefs))
                else:
                  would_be_correct = grouping_is_stable(
                    alt_prefs, string_to_grouping(grouping))
          
          features[m][j].append((length, manual_frs_search,
            rating_set_to_string(true_ratings),
            rating_set_to_string(false_ratings),
            str(would_be_correct), rs_to_report))
    
    for m in range(len(mps_frame_indices)):
      i = mps_frame_indices[m]
      features_file = open(features_file_paths[i], 'w')
      
      rs_total = 0
      manual_frs_search_total = 0
      manual_frs_given = 0
      
      for a in range(len(filenames)):
        for j in range(len(repeat_dirs[m])):
          f = features[m][j][a]
          
          if f is None:
            continue
          
          length, manual_frs_search, true_ratings, false_ratings,\
            would_be_correct, rs_to_report = f
          
          if false_ratings != 'None':
            rs_total += 1
          
          if manual_frs_search:
            manual_frs_search_total += 1
            if false_ratings != 'None':
              manual_frs_given += 1
          
          print('%s %s %d %s %s %s %s' % (filenames[a],
            path.basename(repeat_dirs[m][j]), length, manual_frs_search,
            true_ratings, false_ratings, would_be_correct),
            file=features_file)
      
      features_file.close()
      '''
      if manual_frs_search_total > 0:
        makedirs(manual_frs_paths[i], exist_ok=True)
        
        for k in range(len(filenames)):
          filename = filenames[k]
          for j in range(len(repeat_dirs[m])):
            f = features[m][j][k]
            ev = evals[m][j][k]
            if f is None or ev is None:
              continue
            
            repeat = path.basename(repeat_dirs[m][j])
            mfrs_file_path = path.join(manual_frs_paths[i],
                                       '%s_%s.txt' % (filename, repeat))
            manual_frs_search = f[1]
            if not manual_frs_search:
              if path.exists(mfrs_file_path):
                remove(mfrs_file_path)
              continue
            
            mfrs_key = (filename, repeat)
            if mfrs_key in manual_frs[m]:
              assessment = ratings_to_string(manual_frs[m][mfrs_key])
            else:
              assessment = 'N/A'
            
            mfrs_file = open(mfrs_file_path, 'w', encoding='utf-8')
            
            mfrs_file.close()
      '''
      if rs_total - manual_frs_given > 0:
        makedirs(path.dirname(false_rs_file_paths[i]), exist_ok=True)
        false_rs_file = open(false_rs_file_paths[i], 'w', encoding='utf-8')
        
        for a in range(len(filenames)):
          for j in range(len(repeat_dirs[m])):
            f = features[m][j][a]
            if f is None:
              continue
            
            rs_to_report = f[5]
            if rs_to_report is None or len(rs_to_report) == 0:
              continue
            
            repeat = path.basename(repeat_dirs[m][j])
            overrides_key = (filenames[k], repeat)
            if overrides_key in overrides[m]:
              file_overrides = overrides[m][overrides_key]
            else:
              file_overrides = None
            
            print('%s %s' % (filenames[a], path.basename(repeat_dirs[m][j])),
                  file=false_rs_file)
            print('', file=false_rs_file)
            
            for line_index in sorted(rs_to_report.keys()):
              line, statements = rs_to_report[line_index]
              print('Line %d' % (line_index + 1), file=false_rs_file)
              print(line, file=false_rs_file)
              print('', file=false_rs_file)
              print('False ratings:', file=false_rs_file)
              
              for statement in sorted(statements.keys()):
                e1, e2, v = statement
                e1 = index_chars[e1]
                e2 = index_chars[e2]
                
                assessment = 'N/A'
                if file_overrides is not None and line_index in file_overrides:
                  line_overrides = file_overrides[line_index]
                  if statement in line_overrides:
                    assessment = line_overrides[statement]
                
                print('%s -> %s: %d [Manual assessment: %s]'\
                      % (e1, e2, v, assessment), file=false_rs_file)
              
              print('', file=false_rs_file)
            
            print('---', file=false_rs_file)
            print('', file=false_rs_file)
        
        false_rs_file.close()
